protein_code:
  'negative_BSA'
6560c_BSA:
  vin_interp: 201
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.01 #0.05-0.1
  high_dt_bound: 0.01 #0.05-0.1
  other_dt_bound: 0.01
  amp_low: 0.0
  amp_high: 1.01
  std_low: 0.5 #0.0-0.8
  std_high: 1.1 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 4000
  plot_high: 8000
  subtract: True #always true
  ccs: True
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: [0]
  add_std: 1.1
  extra_name: "10V_16+"
BSA:
  vin_interp: 201
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.01 #0.05-0.1
  high_dt_bound: 0.01 #0.05-0.1
  other_dt_bound: 0.0.01
  amp_low: 0.0
  amp_high: 1.01
  std_low: 0.5 #0.0-0.8
  std_high: 1.1 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 4000
  plot_high: 8000
  subtract: True #always true
  ccs: True
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: [0]
  add_std: 1.1
  extra_name: "17+"
Old_BSA:
  vin_interp: 201
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.01 #0.05-0.1
  high_dt_bound: 0.01 #0.05-0.1
  other_dt_bound: 0.0.01
  amp_low: 0.0
  amp_high: 1.01
  std_low: 0.5 #0.0-0.8
  std_high: 1.01 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 0
  plot_high: 15
  subtract: True #always true
  ccs: False
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: []
  add_std: 1.1
  extra_name: "marieruth_17+"
negative_BSA:
  vin_interp: 60
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.4 #0.05-0.1
  high_dt_bound: 0.4 #0.05-0.1
  other_dt_bound: 0.0.01
  amp_low: 0.0
  amp_high: 1.2
  std_low: 0.3 #0.0-0.8
  std_high: 1.1 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 3000
  plot_high: 5000
  subtract: True #always true
  ccs: False
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: []
  add_std: 1.1
  extra_name: "neg_14+"
positive_BSA:
  vin_interp: 60
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.01 #0.05-0.1
  high_dt_bound: 0.01 #0.05-0.1
  other_dt_bound: 0.0.01
  amp_low: 0.0
  amp_high: 1.1
  std_low: 0.5 #0.0-0.8
  std_high: 0.7 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 3000
  plot_high: 8000
  subtract: True #always true
  ccs: False
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: []
  add_std: 1.1
  extra_name: "pos_17+"
NIST_mAb:
  vin_interp: 201
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.1 #0.05-0.1
  high_dt_bound: 0.05 #0.05-0.1
  other_dt_bound: 0.5
  amp_low: 0.0
  amp_high: 1.01
  std_low: 0.0 #0.0-0.8
  std_high: 2 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 6000
  plot_high: 14000
  subtract: True #always true
  ccs: True
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: [2]
  add_std: 1.1
  extra_name: "29+"
NIST_mAb_fab:
  vin_interp: 201
  dt_interp_factor: 5
  savgol_smooth_window: 11 #5/7
  savgol_smooth_order: 3 # 1/3 
  choice_val: 1.0
  low_dt_bound: 0.1 #0.05-0.1
  high_dt_bound: 0.1 #0.05-0.1
  other_dt_bound: 0.1
  amp_low: 0.0
  amp_high: 2.1
  std_low: 0.0 #0.0-0.8
  std_high: 2 #set to 0.9ish to underaccount/fit both the gaussian and the noise, 1.1/1.2 for the reverse
  after_vin: 200 #set to cut off breakdowncurve if fragmentation is seen-- tune for first 1-2 transitions
  plot_low: 5000
  plot_high: 10000
  subtract: True #always true
  ccs: True
  gaussian_file: "All_gaussians.csv"
  feature_file: "All-features.csv"
  add_in: [1,2]
  add_std: 1.1
  extra_name: "reredo_20+"
