#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Fri May 24 11:13:47 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# wxmplotpanel imports
# Copyright (c) 2024 James S. Prell, all rights reserved
import wxmplot
import spa_avg as spaavg
# end wxGlade


class pnl_Plot(wxmplot.PlotPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: pnl_Plot.__init__
        # wxmplotpanel before lines
        args = args[:-1]  # remove unwanted id argument
        # might want kwds['output_title'] or kwds['show_config_popup'] as options
        kwds["style"] = kwds.get("style", 0) | wx.BORDER_SIMPLE
        wxmplot.PlotPanel.__init__(self, *args, **kwds)
        self.SetMinSize((400, 561))
        self.SetToolTip("Calculated results are plotted here")
        self.Layout()
        # wxmplotpanel after lines
        # these could be member functions of PlotPanel to complete the init
        # end wxGlade

# end of class pnl_Plot

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        # Ken before code for main frame
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((900, 600))
        self.SetTitle("Spa_avg_GUI")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("ionspa\\Spa.bmp", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        self.ctrl_panel = wx.Panel(self.panel_1, wx.ID_ANY)
        self.ctrl_panel.SetMinSize((208, 561))
        sizer_1.Add(self.ctrl_panel, 25, wx.EXPAND | wx.FIXED_MINSIZE | wx.LEFT, 7)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.cell_panel = wx.Panel(self.ctrl_panel, wx.ID_ANY)
        self.cell_panel.SetToolTip("cell properties")
        sizer_2.Add(self.cell_panel, 1, wx.EXPAND, 0)

        self.sz_cell = wx.StaticBoxSizer(wx.StaticBox(self.cell_panel, wx.ID_ANY, "Cell"), wx.VERTICAL)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_5, 1, wx.EXPAND, 0)

        lbl_type = wx.StaticText(self.cell_panel, wx.ID_ANY, "type")
        lbl_type.SetMinSize((80, 16))
        sizer_5.Add(lbl_type, 0, 0, 0)

        self.inp_type = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "cell", style=wx.TE_READONLY)
        sizer_5.Add(self.inp_type, 0, 0, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_6, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.cell_panel, wx.ID_ANY, "L [m]")
        label_1.SetMinSize((80, 16))
        label_1.SetToolTip("Length of the collision cell")
        sizer_6.Add(label_1, 0, 0, 0)

        self.inp_L = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "0.18")
        self.inp_L.SetToolTip("Length of the collision cell")
        sizer_6.Add(self.inp_L, 0, 0, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_7, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.cell_panel, wx.ID_ANY, "E [V/m]")
        label_2.SetMinSize((80, 16))
        label_2.SetToolTip("Constant axial electric field through the length of the cell")
        sizer_7.Add(label_2, 0, 0, 0)

        self.inp_E = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "38.888")
        self.inp_E.SetToolTip("Constant axial electric field through the length of the cell")
        sizer_7.Add(self.inp_E, 0, 0, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_8, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.cell_panel, wx.ID_ANY, "Mg [Da]")
        label_3.SetMinSize((80, 16))
        label_3.SetToolTip("Mass of the collision cell gas")
        sizer_8.Add(label_3, 0, 0, 0)

        self.inp_Mg = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "28")
        self.inp_Mg.SetToolTip("Mass of the collision cell gas")
        sizer_8.Add(self.inp_Mg, 0, 0, 0)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_9, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.cell_panel, wx.ID_ANY, "rho [kg/m^3]")
        label_4.SetMinSize((80, 16))
        label_4.SetToolTip("Density of the gas in the collision cell")
        sizer_9.Add(label_4, 0, 0, 0)

        self.inp_rho = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "2.712e-5")
        self.inp_rho.SetToolTip("Density of the gas in the collision cell")
        sizer_9.Add(self.inp_rho, 0, 0, 0)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_10, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.cell_panel, wx.ID_ANY, "Tg [K]")
        label_5.SetMinSize((80, 16))
        label_5.SetToolTip("Collision cell (gas) temperature")
        sizer_10.Add(label_5, 0, 0, 0)

        self.inp_Tg = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "300")
        self.inp_Tg.SetToolTip("Collision cell (gas) temperature")
        sizer_10.Add(self.inp_Tg, 0, 0, 0)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_cell.Add(sizer_11, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.cell_panel, wx.ID_ANY, "Voff [V]")
        label_6.SetMinSize((80, 16))
        label_6.SetToolTip("Offset voltage added to the injection voltage to impart initial ion energy\nUse this to correct for any instrument offset in collision energy as displayed")
        sizer_11.Add(label_6, 0, 0, 0)

        self.inp_Voff = wx.TextCtrl(self.cell_panel, wx.ID_ANY, "0")
        self.inp_Voff.SetToolTip("Offset voltage added to the injection voltage to impart initial ion energy")
        sizer_11.Add(self.inp_Voff, 0, 0, 0)

        self.ion_panel = wx.Panel(self.ctrl_panel, wx.ID_ANY)
        self.ion_panel.SetToolTip("Ion properties")
        sizer_2.Add(self.ion_panel, 1, wx.EXPAND, 0)

        self.sz_ion = wx.StaticBoxSizer(wx.StaticBox(self.ion_panel, wx.ID_ANY, "Ion"), wx.VERTICAL)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_12, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.ion_panel, wx.ID_ANY, "name")
        label_13.SetMinSize((80, 16))
        label_13.SetToolTip("Name given to the ion")
        sizer_12.Add(label_13, 0, 0, 0)

        self.inp_iname = wx.TextCtrl(self.ion_panel, wx.ID_ANY, "peptide")
        self.inp_iname.SetToolTip("Ion name")
        sizer_12.Add(self.inp_iname, 0, 0, 0)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_13, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.ion_panel, wx.ID_ANY, "Mi [kDa]")
        label_12.SetMinSize((80, 16))
        label_12.SetToolTip("Ion mass")
        sizer_13.Add(label_12, 0, 0, 0)

        self.inp_Mi = wx.TextCtrl(self.ion_panel, wx.ID_ANY, "17.594")
        self.inp_Mi.SetToolTip("Ion mass")
        sizer_13.Add(self.inp_Mi, 0, 0, 0)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_14, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.ion_panel, wx.ID_ANY, "charge [Z/e]")
        label_11.SetMinSize((80, 16))
        label_11.SetToolTip("Ion charge")
        sizer_14.Add(label_11, 0, 0, 0)

        self.inp_charge = wx.TextCtrl(self.ion_panel, wx.ID_ANY, "7")
        self.inp_charge.SetToolTip("Ion charge")
        sizer_14.Add(self.inp_charge, 0, 0, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_15, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.ion_panel, wx.ID_ANY, "atoms")
        label_10.SetMinSize((80, 16))
        label_10.SetToolTip("Number of atoms in the ion")
        sizer_15.Add(label_10, 0, 0, 0)

        self.inp_Natoms = wx.TextCtrl(self.ion_panel, wx.ID_ANY, "1694")
        self.inp_Natoms.SetToolTip("Number of atoms in the ion")
        sizer_15.Add(self.inp_Natoms, 0, 0, 0)

        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_16, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.ion_panel, wx.ID_ANY, "CCS [nm^2]")
        label_9.SetMinSize((80, 16))
        label_9.SetToolTip("Ion collision cross section (with collision gas)")
        sizer_16.Add(label_9, 0, 0, 0)

        self.inp_CCS = wx.TextCtrl(self.ion_panel, wx.ID_ANY, "15.9")
        self.inp_CCS.SetToolTip("Ion collision cross section (with collision gas)")
        sizer_16.Add(self.inp_CCS, 0, 0, 0)

        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_17, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.ion_panel, wx.ID_ANY, "T0 [K]")
        label_8.SetMinSize((80, 16))
        label_8.SetToolTip("Initial internal ion temperature")
        sizer_17.Add(label_8, 0, 0, 0)

        self.inp_Ti = wx.TextCtrl(self.ion_panel, wx.ID_ANY, "300")
        self.inp_Ti.SetToolTip("Initial internal ion temperature")
        sizer_17.Add(self.inp_Ti, 0, 0, 0)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_ion.Add(sizer_18, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.ion_panel, wx.ID_ANY, "hctype")
        label_7.SetMinSize((80, 16))
        label_7.SetToolTip("Ion heat capacity type used in converting between ion energy and temperature")
        sizer_18.Add(label_7, 0, 0, 0)

        self.inp_hctype = wx.Choice(self.ion_panel, wx.ID_ANY, choices=["lipid", "oligonucleotide", "drug", "sugar", "tunemix", "peptide", "peptide90"])
        self.inp_hctype.SetToolTip("Ion heat capacity type\n")
        self.inp_hctype.SetSelection(5)
        sizer_18.Add(self.inp_hctype, 0, 0, 0)

        self.extras_panel = wx.Panel(self.ctrl_panel, wx.ID_ANY)
        sizer_2.Add(self.extras_panel, 1, wx.EXPAND, 0)

        self.sz_run = wx.StaticBoxSizer(wx.StaticBox(self.extras_panel, wx.ID_ANY, "run controls"), wx.VERTICAL)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_run.Add(sizer_19, 1, wx.EXPAND, 0)

        injectV = wx.StaticText(self.extras_panel, wx.ID_ANY, "injectV [V]")
        injectV.SetMinSize((80, 16))
        injectV.SetToolTip("Injection voltage to launch ioin into the collision cell")
        sizer_19.Add(injectV, 0, 0, 0)

        self.inp_injectV = wx.TextCtrl(self.extras_panel, wx.ID_ANY, "10.5")
        self.inp_injectV.SetToolTip("Injection voltage to launch ioin into the collision cell")
        sizer_19.Add(self.inp_injectV, 0, 0, 0)

        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_run.Add(sizer_20, 1, wx.EXPAND, 0)

        calcoption = wx.StaticText(self.extras_panel, wx.ID_ANY, "calc option")
        calcoption.SetMinSize((80, 16))
        calcoption.SetToolTip("Calculation option.  The expected best option is IICT.")
        sizer_20.Add(calcoption, 0, 0, 0)

        self.inp_calcoption = wx.Choice(self.extras_panel, wx.ID_ANY, choices=["IICT", "ELASTIC", "ELASTICHO", "INELTH"])
        self.inp_calcoption.SetToolTip("Select calculation mode: IICT for Improved Inelastic Collision Theory, ELASTIC for fully elastic model, ELASTICHO for elastic with head-on collisions or INELTH for inelastic thermalizing models.")
        self.inp_calcoption.SetSelection(0)
        sizer_20.Add(self.inp_calcoption, 0, 0, 0)

        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_run.Add(sizer_21, 1, wx.EXPAND, 0)

        xaxis = wx.StaticText(self.extras_panel, wx.ID_ANY, "X axis")
        xaxis.SetMinSize((80, 16))
        xaxis.SetToolTip("Horizontal axis data selection")
        sizer_21.Add(xaxis, 0, 0, 0)

        self.inp_xaxis = wx.Choice(self.extras_panel, wx.ID_ANY, choices=["t", "coll", "zp"])
        self.inp_xaxis.SetToolTip("Horizontal axis data selection")
        self.inp_xaxis.SetSelection(0)
        sizer_21.Add(self.inp_xaxis, 0, 0, 0)

        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        self.sz_run.Add(sizer_22, 1, wx.EXPAND, 0)

        yaxis = wx.StaticText(self.extras_panel, wx.ID_ANY, "Y axis")
        yaxis.SetMinSize((80, 16))
        yaxis.SetToolTip("Vertical axis data selection")
        sizer_22.Add(yaxis, 0, 0, 0)

        self.inp_yaxis = wx.Choice(self.extras_panel, wx.ID_ANY, choices=["Ti", "coll", "KE", "ui", "chi", "zp"])
        self.inp_yaxis.SetToolTip("Vertical axis data selection\n")
        self.inp_yaxis.SetSelection(0)
        sizer_22.Add(self.inp_yaxis, 0, 0, 0)

        self.btn_panel = wx.Panel(self.ctrl_panel, wx.ID_ANY)
        sizer_2.Add(self.btn_panel, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)

        """
         in lambda below, arg is the event object (not useful?) and self is the frame object where the lambda was defined
         the frame object contains all the form entry objects:
         btn_addplot, btn_panel, btn_plot, cell_panel, ctrl_panel, extras_panel, inp_CCS, inp_E, inp_L, inp_Mg, 
         inp_Mi, inp_Natoms, inp_Tg, inp_Ti, inp_Voff, inp_calcoption, inp_charge, inp_hctype, inp_iname, 
         inp_injectV, inp_rho, inp_type, inp_xaxis, inp_yaxis, ion_panel, panel_1, plot_panel, sz_cell, sz_ion, sz_run
        --- with the self.plot_panel, this is the wxmplot.PlotPanel object, which will be used to update the plot.
        """
        # this lambda is a hack to override the wxglade generated On_Plot handler and call my own function in an external module
        # self.On_Plot = lambda x: print(f'arg: {x}    self: {self}')
        self.btn_plot = wx.Button(self.btn_panel, wx.ID_ANY, "Plot")
        self.btn_plot.SetToolTip("Run model and plot results")
        sizer_3.Add(self.btn_plot, 0, 0, 0)

        self.btn_addplot = wx.Button(self.btn_panel, wx.ID_ANY, "Add plot")
        self.btn_addplot.SetToolTip("Run model and add to the current plot")
        sizer_3.Add(self.btn_addplot, 0, 0, 0)

        self.plot_panel = pnl_Plot(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.plot_panel, 75, wx.EXPAND | wx.RIGHT, 1)

        self.btn_panel.SetSizer(sizer_3)

        self.extras_panel.SetSizer(self.sz_run)

        self.ion_panel.SetSizer(self.sz_ion)

        self.cell_panel.SetSizer(self.sz_cell)

        self.ctrl_panel.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # Ken after code for main frame

        self.Bind(wx.EVT_BUTTON, self.On_Plot, self.btn_plot)
        self.Bind(wx.EVT_BUTTON, self.On_AddPlot, self.btn_addplot)
        self.Bind(wx.EVT_CLOSE, self.On_Close, self)
        self.Bind(wx.EVT_MENU_CLOSE, self.On_Close, self)
        # end wxGlade

    def getCelldict(self):
        cell_dict = {
            "type": self.inp_type.Value,
            "Mgamu": float(self.inp_Mg.Value),
            "L": float(self.inp_L.Value), 
            "E": float(self.inp_E.Value),
            "rho": float(self.inp_rho.Value),
            "T": float(self.inp_Tg.Value),
            "Voffset": float(self.inp_Voff.Value)
        }
        return cell_dict
    
    def getIondict(self):
        ion_dict = {
            "name": self.inp_iname.Value,
            "mass": float(self.inp_Mi.Value),
            "charge": float(self.inp_charge.Value),
            "num_atoms": float(self.inp_Natoms.Value),
            "CCS": float(self.inp_CCS.Value),
            "T0": float(self.inp_Ti.Value),
            "hcprofname": self.inp_hctype.GetStringSelection()
        }
        return ion_dict

    def get_RunParams(self):
        injectV = float(self.inp_injectV.Value)
        xaxis = self.inp_xaxis.GetStringSelection()
        yaxis = self.inp_yaxis.GetStringSelection()
        calcoption = self.inp_calcoption.GetStringSelection()
        return injectV, xaxis, yaxis, calcoption

    def On_Plot(self, event):  # wxGlade: MyFrame.<event_handler>
        """btn_addplot, btn_panel, btn_plot, cell_panel, ctrl_panel, extras_panel, inp_CCS, inp_E, inp_L, inp_Mg, 
         inp_Mi, inp_Natoms, inp_Tg, inp_Ti, inp_Voff, inp_calcoption, inp_charge, inp_hctype, inp_iname, 
         inp_injectV, inp_rho, inp_type, inp_xaxis, inp_yaxis, ion_panel, panel_1, plot_panel, sz_cell, sz_ion, sz_run
        """
        celld = self.getCelldict()
        iond = self.getIondict()
        injectV, xaxis, yaxis, calcoption = self.get_RunParams()

        paramd = dict(cell=celld, ion=iond, injectV=injectV, option=calcoption, plotfile='none')
        retvals, postdlist = spaavg.main(**paramd)
        xvals, yvals, pltxlabel, pltylabel = getplotinfo(retvals, xaxis, yaxis)
        self.plot_panel.plot(xvals, yvals, title=iond['name'], xlabel=pltxlabel, ylabel=pltylabel)
        event.Skip()

    def On_AddPlot(self, event):  # wxGlade: MyFrame.<event_handler>
        celld = self.getCelldict()
        iond = self.getIondict()
        injectV, xaxis, yaxis, calcoption = self.get_RunParams()

        paramd = dict(cell=celld, ion=iond, injectV=injectV, option=calcoption, plotfile='none')
        retvals, postdlist = spaavg.main(**paramd)
        xvals, yvals, pltxlabel, pltylabel = getplotinfo(retvals, xaxis, yaxis)
        self.plot_panel.oplot(xvals, yvals, title=iond['name'], xlabel=pltxlabel, ylabel=pltylabel)
        event.Skip()

    def On_Close(self, event):  # wxGlade: MyFrame.<event_handler>
        self.Destroy()
        exit()
        event.Skip()
# end of class MyFrame

def getplotinfo(tlogger, xaxis, yaxis):
    if xaxis == 't':
        xvals = tlogger.t
        pltxlabel = 't [s]'
    elif xaxis == 'coll':
        xvals = tlogger.coll
        pltxlabel = 'collisions'
    elif xaxis == 'zp':
        xvals = tlogger.zp
        pltxlabel = 'z position [m]'

    # add other possible y values options here
    if yaxis == 'Ti':
        yvals = tlogger.Ti
        pltylabel = 'T [K]'
    elif yaxis == 'coll':
        yvals = tlogger.coll
        pltylabel = 'collisions'
    elif yaxis == 'KE':
        yvals = tlogger.KE
        pltylabel = 'KE [eV]'
    elif yaxis == 'ui':
        yvals = tlogger.ui
        pltylabel = 'ui [eV]'
    elif yaxis == 'chi':
        yvals = tlogger.chi
        pltylabel = 'chi'
    elif yaxis == 'zp':
        yvals = tlogger.zp
        pltylabel = 'z position [m]'

    return xvals, yvals, pltxlabel, pltylabel


class MyApp(wx.App):
    def OnInit(self):
        self.frame_spa_avg = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_spa_avg)
        self.frame_spa_avg.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    spa_avg_GUI = MyApp(0)
    spa_avg_GUI.MainLoop()
